"
EmptyFule
"
Class {
	#name : 'EmptyFule',
	#superclass : 'Object',
	#category : 'IngSoft2-Model',
	#package : 'IngSoft2-Model'
}

{ #category : 'accessing' }
EmptyFule >> current [
^0.
]

{ #category : 'action' }
EmptyFule >> giveFuel: remainingDistance [

]

{ #category : 'testing' }
EmptyFule >> hasFuelToPlay [

   ^ false.

]

{ #category : 'testing' }
EmptyFule >> isBiggerThanCero [
^false.
]
